import { z } from 'zod';

export const EvidenceSchema = z.object({
  value: z.any().nullable(),
  unit: z.string().optional(),
  source_name: z.string(),
  source_url: z.string(),
  source_type: z.enum(['api', 'open_data', 'pdf', 'html', 'manual', 'derived']),
  scope: z.enum(['official', 'informational', 'market_practice', 'estimate']),
  observed_at: z.string().optional(),
  retrieved_at: z.string(),
  effective_from: z.string().optional(),
  effective_to: z.string().optional(),
  confidence: z.enum(['high', 'medium', 'low', 'unknown']),
  staleness_policy: z.string().optional(),
  refresh_ttl_by_source: z.string().optional(),
  license: z.string().optional(),
  terms_url: z.string().optional(),
  manual_review_required: z.boolean().optional(),
  notes: z.array(z.string()).optional(),
});

export const PropertyCaseSchema = z.object({
  case_id: z.string(),
  source: z.object({
    portal: z.string().nullable().optional(),
    listing_url: z.string().nullable().optional(),
    source_id: z.string().nullable().optional(),
    collected_at: z.string(),
    last_verified_at: z.string().optional(),
    listing_status: z.enum(['active', 'under_offer', 'sold', 'withdrawn', 'unknown']).optional(),
  }),
  identity: z.object({
    raw_address: z.string().nullable().optional(),
    normalized_address: z.string().nullable().optional(),
    postal_code: z.string().nullable().optional(),
    municipality: z.string().nullable().optional(),
    region: z.enum(['WAL', 'VLG', 'BRU']).nullable().optional(),
    country: z.string(),
    lat: z.number().nullable().optional(),
    lng: z.number().nullable().optional(),
    geocode_precision: z.string().nullable().optional(),
    district: z.string().nullable().optional(),
    parcel_id: z.string().nullable().optional(),
    building_id: z.string().nullable().optional(),
    unit_id: z.string().nullable().optional(),
    identity_confidence: z.enum(['high', 'medium', 'low', 'unknown']).optional(),
    identity_conflicts: z.array(z.string()).optional(),
  }),
  listing: z.object({
    title: z.string().nullable().optional(),
    raw_description: z.string().nullable().optional(),
    cleaned_description: z.string().nullable().optional(),
    images: z.array(z.string()).optional(),
    plans: z.array(z.string()).optional(),
    attached_documents: z.array(z.string()).optional(),
    seller_contact: z.string().nullable().optional(),
  }),
  typology: z.object({
    property_kind: z.enum(['house', 'apartment', 'income_building', 'land', 'mixed']).nullable().optional(),
    condition_kind: z.enum(['new', 'old', 'renovated', 'structural_renovation', 'ruin', 'unknown']).nullable().optional(),
    construction_year: z.number().nullable().optional(),
    renovation_year: z.number().nullable().optional(),
    facades_count: z.number().nullable().optional(),
    living_area_m2: z.number().nullable().optional(),
    land_area_m2: z.number().nullable().optional(),
    basement_area_m2: z.number().nullable().optional(),
    attic_area_m2: z.number().nullable().optional(),
    garage_area_m2: z.number().nullable().optional(),
    terrace_area_m2: z.number().nullable().optional(),
    garden_area_m2: z.number().nullable().optional(),
    bedrooms: z.number().nullable().optional(),
    bathrooms: z.number().nullable().optional(),
    wc_count: z.number().nullable().optional(),
    floor: z.number().nullable().optional(),
    has_elevator: z.boolean().nullable().optional(),
    has_basement: z.boolean().nullable().optional(),
    has_attic: z.boolean().nullable().optional(),
    has_parking: z.boolean().nullable().optional(),
    has_garage: z.boolean().nullable().optional(),
    orientation: z.string().nullable().optional(),
    exterior_space: z.string().nullable().optional(),
    condominium: z.boolean().nullable().optional(),
  }),
  economics: z.object({
    asking_price: z.number().nullable().optional(),
    price_history: z.array(z.object({ date: z.string(), price: z.number() })).optional(),
    asking_price_per_m2: z.number().nullable().optional(),
    cadastral_income_if_listed: z.number().nullable().optional(),
    condo_charges: z.number().nullable().optional(),
    reserve_fund: z.number().nullable().optional(),
    working_fund: z.number().nullable().optional(),
    current_rent_if_occupied: z.number().nullable().optional(),
    availability: z.string().nullable().optional(),
    occupancy_status: z.string().nullable().optional(),
    lease_status: z.string().nullable().optional(),
    advertised_yield: z.number().nullable().optional(),
  }),
  technical: z.object({}).catchall(z.any()).optional().default({}),
  energy: z.object({
    label: z.string().nullable().optional(),
    kwh_m2_year: z.number().nullable().optional(),
    certificate_number: z.string().nullable().optional(),
    certificate_date: z.string().nullable().optional(),
    certificate_valid_until: z.string().nullable().optional(),
    certificate_recommendations: z.array(z.string()).optional(),
    regional_obligations: z.array(z.string()).optional(),
  }).catchall(z.any()).default({}),
  meta: z.object({
    workflow_state: z.string().optional(),
  }).catchall(z.any()).default({}),
}).passthrough();

export const BorrowerProfileSchema = z.object({
  borrower: z.object({
    identity: z.object({}).catchall(z.any()),
    contact: z.object({}).catchall(z.any()).optional().default({}),
    employment: z.object({}).catchall(z.any()).optional().default({}),
    income: z.object({}).catchall(z.any()).optional().default({}),
    assets: z.object({}).catchall(z.any()).optional().default({}),
    liabilities: z.object({}).catchall(z.any()).optional().default({}),
    monthly_life: z.object({}).catchall(z.any()).optional().default({}),
  }),
});

export const StrategySchema = z.object({
  strategy: z.object({}).catchall(z.any()),
});

export const LendersSchema = z.object({
  selected_default_lender: z.string(),
  lenders: z.array(z.object({}).catchall(z.any())),
});
